name: piper-dev

services:
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: piper-base:latest
    env_file:
      - .env

  luigi-scheduler:
    build:
      context: .
      dockerfile: docker/luigi-scheduler.Dockerfile
    image: piper-scheduler:latest 
    depends_on:
      - base
    networks:
      - bridged-default
    ports:
      - "8082:8082"

  luigi-worker:
    build:
      context: .
      dockerfile: docker/luigi-worker.Dockerfile
    image: piper-worker:latest
    command: /app/luigi_worker.sh
    depends_on:
      - luigi-scheduler
    networks:
      - bridged-default
    environment:
      - PYTHONUNBUFFERED=1
      - LUIGI_SCHEDULER_HOST=luigi-scheduler
      - LUIGI_SCHEDULER_PORT=8082

  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    image: piper-orchestrator:latest
    depends_on:
      - base
      - luigi-scheduler
    networks:
      - bridged-default
    environment:
      - PYTHONUNBUFFERED=1
      - LUIGI_SCHEDULER_HOST=luigi-scheduler

networks:
  bridged-default:
    driver: bridge